/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import { Contract, ContractFactory, ContractTransactionResponse, Interface } from 'ethers';
import type { Signer, ContractDeployTransaction, ContractRunner } from 'ethers';
import type { NonPayableOverrides } from '../common';
import type { GameScore, GameScoreInterface } from '../GameScore';

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'player',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'score',
        type: 'uint256',
      },
    ],
    name: 'NewHighScore',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'highScores',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_score',
        type: 'uint256',
      },
    ],
    name: 'submitScore',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

const _bytecode =
  '0x608060405234801561001057600080fd5b506102d2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100355760003560e01c8062d8e1041461003a578063aff0b2971461006a575b600080fd5b610054600480360381019061004f91906101e2565b610086565b6040516100619190610228565b60405180910390f35b610084600480360381019061007f919061026f565b61009e565b005b60006020528060005260406000206000915090505481565b60003390506000808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205482111561017b57816000808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508073ffffffffffffffffffffffffffffffffffffffff167fe265ae360c48dc3c258727b698cc5a994da69b0d32354166f39003a488919443836040516101729190610228565b60405180910390a25b5050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101af82610184565b9050919050565b6101bf816101a4565b81146101ca57600080fd5b50565b6000813590506101dc816101b6565b92915050565b6000602082840312156101f8576101f761017f565b5b6000610206848285016101cd565b91505092915050565b6000819050919050565b6102228161020f565b82525050565b600060208201905061023d6000830184610219565b92915050565b61024c8161020f565b811461025757600080fd5b50565b60008135905061026981610243565b92915050565b6000602082840312156102855761028461017f565b5b60006102938482850161025a565b9150509291505056fea264697066735822122085daea72d9d1155767d1f72dcfe98553993e87503f62461cd3070cd224a2070264736f6c63430008180033';

type GameScoreConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GameScoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GameScore__factory extends ContractFactory {
  constructor(...args: GameScoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GameScore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GameScore__factory {
    return super.connect(runner) as GameScore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GameScoreInterface {
    return new Interface(_abi) as GameScoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GameScore {
    return new Contract(address, _abi, runner) as unknown as GameScore;
  }
}
