/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gameScoreSol from "./GameScore.sol";
export { SnakeGameScore__factory } from "./SnakeGameScore__factory";
