/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameScoreSol from "./GameScore.sol";
export type { gameScoreSol };
export type { SnakeGameScore } from "./SnakeGameScore";
export * as factories from "./factories";
export type { SnakeGameLeaderboard } from "./GameScore.sol/SnakeGameLeaderboard";
export { SnakeGameLeaderboard__factory } from "./factories/GameScore.sol/SnakeGameLeaderboard__factory";
export { SnakeGameScore__factory } from "./factories/SnakeGameScore__factory";
